name: Deploy Backend

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    env:
      RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
      RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
    steps:
      - name: Verify Render secrets
        run: |
          if [ -z "$RENDER_SERVICE_ID" ] || [ -z "$RENDER_API_KEY" ]; then
            echo "RENDER_SERVICE_ID or RENDER_API_KEY is not set; skipping deployment.";
            exit 0;
          fi

      - name: Trigger Render deploy
        uses: render-actions/deploy@v1
        with:
          service-id: ${{ env.RENDER_SERVICE_ID }}
          api-key: ${{ env.RENDER_API_KEY }}
